name = "Astrodynamics"

[uuid]
3ef73b0c-6d60-46a5-a738-1cbd0a6036e3

[authors]
["Yoav Dekel"]

[version]
0.1.0

[deps]
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"

[compat]
julia = "1.6"
SPICE = "0.3" 